-- Camera Shake Asset
-- Generated by NipsEngine Camera Shake Editor

local amplitude = 0.3000
local location_amplitude = 4.9700
local fov_amplitude = 0.0444
local frequency = 15.0000
local duration = 3.7000
-- Rotation Bezier
local cp1x = 0.0000
local cp1y = 0.0000
local cp2x = 0.9922
local cp2y = 0.0000
local cp0y = 0.0000
local cp3y = 0.0000
-- Location Bezier
local loc_cp1x = 0.0469
local loc_cp1y = 0.0000
local loc_cp2x = 1.0000
local loc_cp2y = 0.0000
local loc_cp0y = 0.0000
local loc_cp3y = 0.0000
-- FOV Bezier
local fov_cp1x = 0.0000
local fov_cp1y = 0.4922
local fov_cp2x = 1.0000
local fov_cp2y = 0.5312
local fov_cp0y = 0.5391
local fov_cp3y = 0.5078

local elapsed = 0.0

local function evaluateCubic(t, p0, p1, p2, p3)
    local u = 1.0 - t
    return u*u*u*p0 + 3*u*u*t*p1 + 3*u*t*t*p2 + t*t*t*p3
end

function ModifyCamera(view, deltaTime)
    elapsed = elapsed + deltaTime
    if elapsed >= duration then
        elapsed = 0.0
        return false
    end

    local t = elapsed / duration

    local rot_alpha = evaluateCubic(t, cp0y, cp1y, cp2y, cp3y)
    view.Rotation.X = view.Rotation.X + math.sin(elapsed * frequency)       * amplitude * rot_alpha
    view.Rotation.Y = view.Rotation.Y + math.cos(elapsed * frequency * 0.8) * amplitude * rot_alpha
    view.Rotation.Z = view.Rotation.Z + math.sin(elapsed * frequency * 1.2) * amplitude * rot_alpha

    if location_amplitude ~= 0.0 then
        local loc_alpha = evaluateCubic(t, loc_cp0y, loc_cp1y, loc_cp2y, loc_cp3y)
        view.Location.X = view.Location.X + math.sin(elapsed * frequency * 1.1) * location_amplitude * loc_alpha
        view.Location.Y = view.Location.Y + math.cos(elapsed * frequency * 0.9) * location_amplitude * loc_alpha
        view.Location.Z = view.Location.Z + math.sin(elapsed * frequency * 1.3) * location_amplitude * loc_alpha
    end

    if fov_amplitude ~= 0.0 then
        local fov_alpha = evaluateCubic(t, fov_cp0y, fov_cp1y, fov_cp2y, fov_cp3y)
        view.FOV = view.FOV + math.sin(elapsed * frequency * 0.7) * fov_amplitude * fov_alpha
    end

    return true
end
