-- Camera Shake Asset
-- Generated by NipsEngine Camera Shake Editor

local duration      = 5.0000

-- Rotation (Pitch/Yaw/Roll)
local rot_amp_pitch = 0.0000
local rot_amp_yaw   = 0.0000
local rot_amp_roll  = 0.0000
local rot_freq_pitch= 0.0000
local rot_freq_yaw  = 15.0000
local rot_freq_roll = 15.0000
local rot_cp1x=0.0000 local rot_cp1y=0.4984 local rot_cp2x=1.0000 local rot_cp2y=0.4859 local rot_cp0y=0.5078 local rot_cp3y=0.4844

-- Location (X/Y/Z)
local loc_amp_x     = 0.0000
local loc_amp_y     = 0.0000
local loc_amp_z     = 0.5000
local loc_freq_x    = 0.0000
local loc_freq_y    = 0.0000
local loc_freq_z    = 7.0000
local loc_cp1x=0.0000 local loc_cp1y=0.4594 local loc_cp2x=1.0000 local loc_cp2y=0.4781 local loc_cp0y=0.4688 local loc_cp3y=0.4922

-- FOV
local fov_amplitude = 0.0000
local fov_frequency = 15.0000
local fov_cp1x=0.2500 local fov_cp1y=0.1000 local fov_cp2x=0.7500 local fov_cp2y=0.9000 local fov_cp0y=1.0000 local fov_cp3y=0.0000

local elapsed = 0.0

local function cubic(t, p0, p1, p2, p3)
    local u = 1.0 - t
    return u*u*u*p0 + 3*u*u*t*p1 + 3*u*t*t*p2 + t*t*t*p3
end

function ModifyCamera(view, dt)
    elapsed = elapsed + dt
    if elapsed >= duration then elapsed = 0.0; return false end

    local t = elapsed / duration

    local ra = cubic(t, rot_cp0y, rot_cp1y, rot_cp2y, rot_cp3y)
    view.Rotation.X = view.Rotation.X + math.sin(elapsed * rot_freq_pitch) * rot_amp_pitch * ra
    view.Rotation.Y = view.Rotation.Y + math.cos(elapsed * rot_freq_yaw)   * rot_amp_yaw   * ra
    view.Rotation.Z = view.Rotation.Z + math.sin(elapsed * rot_freq_roll)  * rot_amp_roll  * ra

    if loc_amp_x ~= 0.0 or loc_amp_y ~= 0.0 or loc_amp_z ~= 0.0 then
        local la = cubic(t, loc_cp0y, loc_cp1y, loc_cp2y, loc_cp3y)
        view.Location.X = view.Location.X + math.sin(elapsed * loc_freq_x) * loc_amp_x * la
        view.Location.Y = view.Location.Y + math.cos(elapsed * loc_freq_y) * loc_amp_y * la
        view.Location.Z = view.Location.Z + math.sin(elapsed * loc_freq_z) * loc_amp_z * la
    end

    if fov_amplitude ~= 0.0 then
        local fa = cubic(t, fov_cp0y, fov_cp1y, fov_cp2y, fov_cp3y)
        view.FOV = view.FOV + math.sin(elapsed * fov_frequency) * fov_amplitude * fa
    end

    return true
end
