-- Camera Shake Asset
-- Generated by NipsEngine Camera Shake Editor
return {
    Modifiers = {
        {
            Type         = "Shake",
            Duration     = 5.0000,
            bLoop        = true,

            RotAmplitude = { 0.0000, 0.0000, 0.0000 },
            RotFrequency = { 0.0000, 15.0000, 15.0000 },
            RotBezierCP  = { 0.0000, 0.4984, 1.0000, 0.4859, 0.5078, 0.4844 },

            LocAmplitude = { 0.0000, 0.0000, 0.3000 },
            LocFrequency = { 0.0000, 0.0000, 7.0000 },
            LocBezierCP  = { 0.0000, 0.4594, 1.0000, 0.4781, 0.4688, 0.4922 },

            FOVAmplitude = 0.0000,
            FOVFrequency = 15.0000,
            FOVBezierCP  = { 0.2500, 0.1000, 0.7500, 0.9000, 1.0000, 0.0000 },
        },
    },
}
