#include "Particle/ParticleSystemComponent.h"

#include "Camera/ViewportCamera.h"
#include "GameFramework/AActor.h"
#include "GameFramework/World.h"
#include "Particle/ParticleModuleTypeData.h"
#include "Render/Scene/RenderBus.h"

#include <cstring>

UParticleSystemComponent::UParticleSystemComponent()
{
	SetEnableCull(false);
}

UParticleSystemComponent::~UParticleSystemComponent()
{
	ClearEmitterInstances();
}

// Function : Set particle system template and recreate emitter instances when it changes
// input : InTemplate
// InTemplate : particle system asset to simulate on this component
// output : Template is updated and emitter instances match the new template
void UParticleSystemComponent::SetTemplate(UParticleSystem* InTemplate)
{
	if (Template == InTemplate && !EmitterInstances.empty())
	{
		return;
	}

	Template = InTemplate;
	RecreateEmitterInstances();
}

void UParticleSystemComponent::PostEditProperty(const char* PropertyName)
{
	UPrimitiveComponent::PostEditProperty(PropertyName);

	const bool bTemplateChanged = PropertyName && std::strcmp(PropertyName, "Template") == 0;
	const bool bNeedsRuntimeRebuild = Template && EmitterInstances.empty();
	if (bTemplateChanged || bNeedsRuntimeRebuild)
	{
		RecreateEmitterInstances();
	}
}

// Function : Rebuild emitter instances from current particle system template
// input : None
// output : Existing instances are cleared and one runtime instance is created per template emitter
void UParticleSystemComponent::RecreateEmitterInstances()
{
	ClearEmitterInstances();
	if (!Template)
	{
		return;
	}

	const TArray<UParticleEmitter*>& Emitters = Template->GetEmitters();
	EmitterInstances.reserve(Emitters.size());
	for (int32 Index = 0; Index < static_cast<int32>(Emitters.size()); ++Index)
	{
		UParticleEmitter* EmitterAsset = Emitters[Index];
		// TypeDataModule이 캐싱되어 있도록 보장. Init 내부에서도 다시 호출되지만 idempotent.
		// 명시 호출 이유: LOD0 조회를 Instance 생성 전에 해야 하므로, asset 측 캐시가 stale이면 silent fallback 위험.
		if (EmitterAsset)
		{
			EmitterAsset->CacheEmitterModuleInfo();
		}
		UParticleLODLevel* LOD0 = EmitterAsset ? EmitterAsset->GetLODLevel(0) : nullptr;
		UParticleModuleTypeDataBase* TypeData = LOD0 ? LOD0->GetTypeDataModule() : nullptr;
		// TypeData가 있으면 type별 derived instance 생성 hook 사용. 없으면 base FParticleEmitterInstance.
		// USpriteTypeData::CreateInstance() = new FParticleEmitterInstance() 이므로 Sprite path 회귀 0.
		FParticleEmitterInstance* Instance = TypeData
			? TypeData->CreateInstance(this, Index)
			: new FParticleEmitterInstance();
		Instance->Init(EmitterAsset, this, Index);
		EmitterInstances.push_back(Instance);
	}
}

// Function : Delete all runtime emitter instances and pending particle events
// input : None
// output : EmitterInstances and PendingCollisionEvents become empty
void UParticleSystemComponent::ClearEmitterInstances()
{
	for (FParticleEmitterInstance* Instance : EmitterInstances)
	{
		delete Instance;
	}
	EmitterInstances.clear();
	PendingCollisionEvents.clear();
}

// Function : Compute distance from this particle component to the active camera
// input : None
// output : Distance to active camera, or 0 when no focused world or active camera exists
float UParticleSystemComponent::ComputeEmitterLODDistance() const
{
	const AActor* OwnerActor = GetOwner();
	const UWorld* World = OwnerActor ? OwnerActor->GetFocusedWorld() : nullptr;
	if (!World || !World->GetActiveCamera())
	{
		return 0.0f;
	}

	return FVector::Dist(GetWorldLocation(), World->GetActiveCamera()->GetLocation());
}

// Function : Add particle collision event to component queue
// input : EventData
// EventData : collision event generated by a particle module
// output : EventData is stored until DispatchQueuedParticleEvents is called
void UParticleSystemComponent::QueueCollisionEvent(const FParticleEventCollideData& EventData)
{
	PendingCollisionEvents.push_back(EventData);
}

// Function : Broadcast queued particle collision events and clear the queue
// input : None
// output : OnParticleCollide is broadcast for each queued event and the queue becomes empty
void UParticleSystemComponent::DispatchQueuedParticleEvents()
{
	for (const FParticleEventCollideData& EventData : PendingCollisionEvents)
	{
		OnParticleCollide.Broadcast(EventData);
	}
	PendingCollisionEvents.clear();
}

// Function : Recalculate world bounds from component location and active particle locations
// input : None
// output : WorldAABB contains the component bounds expanded by active particle positions
void UParticleSystemComponent::UpdateWorldAABB() const
{
	WorldAABB.Reset();
	const FVector ComponentLocation = GetWorldLocation();
	WorldAABB.Expand(ComponentLocation - FVector(100.0f, 100.0f, 100.0f));
	WorldAABB.Expand(ComponentLocation + FVector(100.0f, 100.0f, 100.0f));

	for (const FParticleEmitterInstance* Instance : EmitterInstances)
	{
		if (!Instance)
		{
			continue;
		}

		for (int32 ParticleIndex = 0; ParticleIndex < Instance->GetActiveParticleCount(); ++ParticleIndex)
		{
			const FBaseParticle* Particle = Instance->GetParticle(ParticleIndex);
			if (Particle)
			{
				WorldAABB.Expand(Particle->Location);
			}
		}
	}
}

// Function : Test particle system component against a ray
// input : Ray, OutHitResult
// Ray : world ray used for picking or collision query
// OutHitResult : hit result reset by this query
// output : false because particle raycast is not implemented yet
bool UParticleSystemComponent::RaycastMesh(const FRay& Ray, FHitResult& OutHitResult)
{
	(void)Ray;
	OutHitResult.Reset();
	return false;
}

int32 UParticleSystemComponent::GetTotalActiveParticleCount() const
{
	int32 TotalCount = 0;
	for (const FParticleEmitterInstance* Instance : EmitterInstances)
	{
		if (Instance)
		{
			TotalCount += Instance->GetActiveParticleCount();
		}
	}
	return TotalCount;
}

int32 UParticleSystemComponent::GetEmitterInstanceCount() const
{
	return static_cast<int32>(EmitterInstances.size());
}

FParticleEmitterInstance* UParticleSystemComponent::GetEmitterInstance(int32 Index)
{
	if (Index >= 0 && Index < GetEmitterInstanceCount())
	{
		return EmitterInstances[Index];
	}
	return nullptr;
}

const FParticleEmitterInstance* UParticleSystemComponent::GetEmitterInstance(int32 Index) const
{
	if (Index >= 0 && Index < GetEmitterInstanceCount())
	{
		return EmitterInstances[Index];
	}
	return nullptr;
}

// Function : Tick every emitter instance and mark spatial bounds dirty
// input : DeltaTime
// DeltaTime : elapsed time for this component update
// output : Emitter simulations advance and the spatial index is notified for bounds refresh
void UParticleSystemComponent::TickComponent(float DeltaTime)
{
	TickPreview(DeltaTime, true);
}

void UParticleSystemComponent::TickPreview(float DeltaTime, bool bAllowSpawning)
{
	for (FParticleEmitterInstance* Instance : EmitterInstances)
	{
		if (Instance)
		{
			Instance->Tick(DeltaTime, bAllowSpawning);
		}
	}
	NotifySpatialIndexDirty();
}

// Cycle 10c 계층 분리: type-agnostic dispatch hook.
// 모든 emitter instance에 대해 BuildInstanceData() 호출 — instance 내부 buffer만 갱신.
// RenderCommand 매핑은 Builder가 별도로 수행 (Instance/Component는 FRenderCommand 모름).
// 본 함수 본문에 FRenderCommand 참조 0건 — 계층 분리 원칙 (사용자 결정).
void UParticleSystemComponent::BuildInstanceData()
{
	for (FParticleEmitterInstance* Instance : EmitterInstances)
	{
		if (Instance)
		{
			Instance->BuildInstanceData();
		}
	}
}

// Function : Cache RenderBus camera state for derived BuildInstanceData consumption (Cycle 14, 결정 18 β)
// input : InRenderBus
// InRenderBus : RenderBus belonging to the current render frame
// output : CachedCamera* members are populated and bCachedCameraValid is set true
//
// Builder 가 ParticleSystemComponent->BuildInstanceData() 호출 직전에 호출.
// derived Mesh instance::BuildInstanceData 가 GetOwningComponent() 통해 cache 를 read.
// signature 변경 0건 보장 (옵션 α 회피) — 본 메서드는 BuildInstanceData 와 별도 진입점.
void UParticleSystemComponent::CacheCameraFromRenderBus(const FRenderBus& InRenderBus)
{
	CachedCameraPosition = InRenderBus.GetCameraPosition();
	CachedCameraForward = InRenderBus.GetCameraForward();
	CachedCameraUp = InRenderBus.GetCameraUp();
	CachedCameraRight = InRenderBus.GetCameraRight();
	bCachedCameraValid = true;
}
