#include "Particle/ParticleSystemComponent.h"

#include "Camera/ViewportCamera.h"
#include "GameFramework/AActor.h"
#include "GameFramework/World.h"

UParticleSystemComponent::~UParticleSystemComponent()
{
	ClearEmitterInstances();
}

// Function : Set particle system template and recreate emitter instances when it changes
// input : InTemplate
// InTemplate : particle system asset to simulate on this component
// output : Template is updated and emitter instances match the new template
void UParticleSystemComponent::SetTemplate(UParticleSystem* InTemplate)
{
	if (Template == InTemplate)
	{
		return;
	}

	Template = InTemplate;
	RecreateEmitterInstances();
}

// Function : Rebuild emitter instances from current particle system template
// input : None
// output : Existing instances are cleared and one runtime instance is created per template emitter
void UParticleSystemComponent::RecreateEmitterInstances()
{
	ClearEmitterInstances();
	if (!Template)
	{
		return;
	}

	const TArray<UParticleEmitter*>& Emitters = Template->GetEmitters();
	EmitterInstances.reserve(Emitters.size());
	for (int32 Index = 0; Index < static_cast<int32>(Emitters.size()); ++Index)
	{
		FParticleEmitterInstance* Instance = new FParticleEmitterInstance();
		Instance->Init(Emitters[Index], this, Index);
		EmitterInstances.push_back(Instance);
	}
}

// Function : Delete all runtime emitter instances and pending particle events
// input : None
// output : EmitterInstances and PendingCollisionEvents become empty
void UParticleSystemComponent::ClearEmitterInstances()
{
	for (FParticleEmitterInstance* Instance : EmitterInstances)
	{
		delete Instance;
	}
	EmitterInstances.clear();
	PendingCollisionEvents.clear();
}

// Function : Compute distance from this particle component to the active camera
// input : None
// output : Distance to active camera, or 0 when no focused world or active camera exists
float UParticleSystemComponent::ComputeEmitterLODDistance() const
{
	const AActor* OwnerActor = GetOwner();
	const UWorld* World = OwnerActor ? OwnerActor->GetFocusedWorld() : nullptr;
	if (!World || !World->GetActiveCamera())
	{
		return 0.0f;
	}

	return FVector::Dist(GetWorldLocation(), World->GetActiveCamera()->GetLocation());
}

// Function : Add particle collision event to component queue
// input : EventData
// EventData : collision event generated by a particle module
// output : EventData is stored until DispatchQueuedParticleEvents is called
void UParticleSystemComponent::QueueCollisionEvent(const FParticleEventCollideData& EventData)
{
	PendingCollisionEvents.push_back(EventData);
}

// Function : Broadcast queued particle collision events and clear the queue
// input : None
// output : OnParticleCollide is broadcast for each queued event and the queue becomes empty
void UParticleSystemComponent::DispatchQueuedParticleEvents()
{
	for (const FParticleEventCollideData& EventData : PendingCollisionEvents)
	{
		OnParticleCollide.Broadcast(EventData);
	}
	PendingCollisionEvents.clear();
}

// Function : Recalculate world bounds from component location and active particle locations
// input : None
// output : WorldAABB contains the component bounds expanded by active particle positions
void UParticleSystemComponent::UpdateWorldAABB() const
{
	WorldAABB.Reset();
	const FVector ComponentLocation = GetWorldLocation();
	WorldAABB.Expand(ComponentLocation - FVector(100.0f, 100.0f, 100.0f));
	WorldAABB.Expand(ComponentLocation + FVector(100.0f, 100.0f, 100.0f));

	for (const FParticleEmitterInstance* Instance : EmitterInstances)
	{
		if (!Instance)
		{
			continue;
		}

		for (int32 ParticleIndex = 0; ParticleIndex < Instance->GetActiveParticleCount(); ++ParticleIndex)
		{
			const FBaseParticle* Particle = Instance->GetParticle(ParticleIndex);
			if (Particle)
			{
				WorldAABB.Expand(Particle->Location);
			}
		}
	}
}

// Function : Test particle system component against a ray
// input : Ray, OutHitResult
// Ray : world ray used for picking or collision query
// OutHitResult : hit result reset by this query
// output : false because particle raycast is not implemented yet
bool UParticleSystemComponent::RaycastMesh(const FRay& Ray, FHitResult& OutHitResult)
{
	(void)Ray;
	OutHitResult.Reset();
	return false;
}

int32 UParticleSystemComponent::GetTotalActiveParticleCount() const
{
	int32 TotalCount = 0;
	for (const FParticleEmitterInstance* Instance : EmitterInstances)
	{
		if (Instance)
		{
			TotalCount += Instance->GetActiveParticleCount();
		}
	}
	return TotalCount;
}

int32 UParticleSystemComponent::GetEmitterInstanceCount() const
{
	return static_cast<int32>(EmitterInstances.size());
}

FParticleEmitterInstance* UParticleSystemComponent::GetEmitterInstance(int32 Index)
{
	if (Index >= 0 && Index < GetEmitterInstanceCount())
	{
		return EmitterInstances[Index];
	}
	return nullptr;
}

const FParticleEmitterInstance* UParticleSystemComponent::GetEmitterInstance(int32 Index) const
{
	if (Index >= 0 && Index < GetEmitterInstanceCount())
	{
		return EmitterInstances[Index];
	}
	return nullptr;
}

// Function : Tick every emitter instance and mark spatial bounds dirty
// input : DeltaTime
// DeltaTime : elapsed time for this component update
// output : Emitter simulations advance and the spatial index is notified for bounds refresh
void UParticleSystemComponent::TickComponent(float DeltaTime)
{
	for (FParticleEmitterInstance* Instance : EmitterInstances)
	{
		if (Instance)
		{
			Instance->Tick(DeltaTime);
		}
	}
	NotifySpatialIndexDirty();
}

void UParticleSystemComponent::BuildSpriteInstanceData()
{
	const int32 EmitterCount = static_cast<int32>(EmitterInstances.size());
	if (static_cast<int32>(EmitterInstanceData.size()) != EmitterCount)
	{
		EmitterInstanceData.resize(EmitterCount);
	}

	for (int32 EmitterIdx = 0; EmitterIdx < EmitterCount; ++EmitterIdx)
	{
		FParticleEmitterInstance* Instance = EmitterInstances[EmitterIdx];
		TArray<FSpriteParticleInstanceData>& Out = EmitterInstanceData[EmitterIdx];
		Out.clear();

		if (!Instance || Instance->GetActiveParticleCount() == 0)
		{
			continue;
		}

		Out.reserve(Instance->GetActiveParticleCount());
        for (int32 i = 0; i < Instance->GetActiveParticleCount(); ++i)
		{
			const FBaseParticle* Particle = Instance->GetParticle(i);
			if (!Particle)
			{
				continue;
			}

			FSpriteParticleInstanceData Data;
			Data.Position   = Particle->Location;
			Data.Size       = FVector2(Particle->Size.X, Particle->Size.Y);
			Data.Color      = Particle->Color;
			Data.Rotation   = Particle->Rotation;
			Data.SubUVIndex = 0; // TODO: USubUVModule 포팅 후 페이로드에서 추출
			Out.push_back(Data);
		}
	}
}

const TArray<FSpriteParticleInstanceData>& UParticleSystemComponent::GetEmitterInstanceData(int32 EmitterIndex) const
{
	static const TArray<FSpriteParticleInstanceData> Empty;
	if (EmitterIndex < 0 || EmitterIndex >= static_cast<int32>(EmitterInstanceData.size()))
	{
		return Empty;
	}
	return EmitterInstanceData[EmitterIndex];
}
