#include "Particle/ParticleEvent.h"
#include "Particle/ParticleSystemComponent.h"
#include "Particle/ParticleSystem.h"

AParticleEventManager::~AParticleEventManager()
{
	if (PreviewParticleSystem)
	{
		UObjectManager::Get().DestroyObject(PreviewParticleSystem);
		PreviewParticleSystem = nullptr;
	}
}

// Function : Add particle collision event to manager queue
// input : EventData
// EventData : collision event data generated by a particle system component
// output : Collision event is stored until DispatchEvents is called
void AParticleEventManager::PushCollisionEvent(const FParticleEventCollideData& EventData)
{
	CollisionEvents.push_back(EventData);
}

// Function : Broadcast queued particle collision events and clear the queue
// input : None
// output : OnParticleCollide is broadcast for each queued event and the queue becomes empty
void AParticleEventManager::DispatchEvents()
{
	for (const FParticleEventCollideData& EventData : CollisionEvents)
	{
		OnParticleCollide.Broadcast(EventData);
	}
	CollisionEvents.clear();
}

void AParticleEventManager::InitDefaultComponents()
{
    if (PreviewParticleSystem)
    {
        return;
    }

    UParticleSystemComponent* ParticleSystemComponent = AddComponent<UParticleSystemComponent>();
    SetRootComponent(ParticleSystemComponent);

    PreviewParticleSystem = UParticleSystem::CreateDefaultSpriteSystem();
    if (!PreviewParticleSystem)
    {
        return;
    }

    USubUVModule* SubUV = UObjectManager::Get().CreateObject<USubUVModule>();
    SubUV->SetSubUVName(FName("Asset/plasma.png"));
    PreviewParticleSystem->Emitters[0]->LODLevels[0]->Modules.push_back(SubUV);
    PreviewParticleSystem->CacheEmitterModuleInfo();
    ParticleSystemComponent->SetTemplate(PreviewParticleSystem);
    SetTickInEditor(true);
}
	 
