#include "Particle/ParticleEvent.h"

// Function : Add particle collision event to manager queue
// input : EventData
// EventData : collision event data generated by a particle system component
// output : Collision event is stored until DispatchEvents is called
void AParticleEventManager::PushCollisionEvent(const FParticleEventCollideData& EventData)
{
	CollisionEvents.push_back(EventData);
}

// Function : Queue a batch of particle collision events and broadcast them
// input : EventDataList
// EventDataList : collision events drained from a particle system component
// output : OnParticleCollide is broadcast for each event and the manager queue becomes empty
void AParticleEventManager::DispatchCollisionEvents(const TArray<FParticleEventCollideData>& EventDataList)
{
	for (const FParticleEventCollideData& EventData : EventDataList)
	{
		PushCollisionEvent(EventData);
	}
	DispatchEvents();
}

// Function : Broadcast queued particle collision events and clear the queue
// input : None
// output : OnParticleCollide is broadcast for each queued event and the queue becomes empty
void AParticleEventManager::DispatchEvents()
{
	for (const FParticleEventCollideData& EventData : CollisionEvents)
	{
		OnParticleCollide.Broadcast(EventData);
	}
	CollisionEvents.clear();
}

void AParticleEventManager::InitDefaultComponents()
{
	// Dispatcher only. Particle simulation remains owned by UParticleSystemComponent.
}
